import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';
import Header from "../components/layout/Header";
import { Metadata } from 'next';
import Footer from "../components/layout/Footer";
import "../globals.css";

export function generateStaticParams() {
    return [{ locale: 'tr' }, { locale: 'en' }];
}

type LayoutProps = {
    children: React.ReactNode;
    params: Promise<{
        locale: string;
    }>;
};

export const metadata: Metadata = {
  title: "Lux Hotels Project",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
    children,
    params
}: LayoutProps) {
    const { locale } = await params;
    
    let messages;
    try {
        messages = (await import(`../../messages/${locale}.json`)).default;
    } catch {
        notFound();
    }

    return (
        <html lang={locale}>
            <head>
                <meta charSet="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </head>
            <body suppressHydrationWarning>
                <NextIntlClientProvider locale={locale} messages={messages}>
                  <Header />
                  {children}
                  <Footer />
                </NextIntlClientProvider>
            </body>
        </html>
    );
}









